name: redarko
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_text_kit: ^4.2.3
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
